// <auto-generated />
using System;
using CarGarageAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarGarageAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarGarageAPI.Models.Car", b =>
                {
                    b.Property<int>("Vin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vin"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.HasKey("Vin");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Vin = 1,
                            BrandName = "Maruti Suzuki",
                            Colour = "white",
                            ModelName = "Swift",
                            Price = 1000000
                        },
                        new
                        {
                            Vin = 2,
                            BrandName = "Hyundai",
                            Colour = "silver",
                            ModelName = "i20",
                            Price = 1200000
                        },
                        new
                        {
                            Vin = 3,
                            BrandName = "Maruti Suzuki",
                            Colour = "black",
                            ModelName = "WagonR",
                            Price = 800000
                        },
                        new
                        {
                            Vin = 4,
                            BrandName = "Mahindra",
                            Colour = "Grey",
                            ModelName = "Scorpio",
                            Price = 1400000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
